# Generated by Django 4.2 on 2024-10-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'permissions': [('can_enter_book', 'Can enter book')]},
        ),
    ]
