# Generated by Django 4.2.11 on 2024-10-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Author', '0003_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
