# Generated by Django 4.2.11 on 2024-10-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Author', '0004_publisher_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
