# Generated by Django 4.2 on 2024-10-29 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
