# Generated by Django 4.2 on 2024-10-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_publisher_options_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_enter_book', 'Can enter book')]},
        ),
    ]
